version: '3'
services:
  site:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CI # Makes sure Jest doesn't do interactive cli when run in Buildkite
    volumes:
      - "./bundle-analysis:/bundle-analysis"