version: '3.4'

services:
  integration-tests:
    build:
      context: .
      target: integration-tests
    image: "buildkiteci/site:site-build-${BUILDKITE_BUILD_NUMBER}-integration-tests"
    volumes:
      - "./integration-tests:/tests"
    environment:
      - DEBUG
      - IGNORE_HTTPS_ERRORS=true
    links:
      - site

  site:
    build: .
    expose:
      - "3000"
