version: '3.4'
services:
  integration-tests:
    image: "buildkiteci/site:site-build-${BUILDKITE_BUILD_NUMBER}-integration-tests"
    command: "yarn run integration:production"
    environment:
      - DEBUG
      - PERCY_TOKEN
      - PERCY_PROJECT
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_BUILD_ID