version: '3.4'

services:
  integration-tests:
    build:
      context: .
      target: integration-tests
    environment:
      - DEBUG
      - PERCY_TOKEN
      - "TEST_HOST=http://site:3000"
      - IGNORE_HTTPS_ERRORS=true
    links:
      - site

  site:
    build: .
    expose:
      - "3000"
