version: '3.4'
services:
  integration-tests:
    image: "buildkiteci/site:site-build-${BUILDKITE_BUILD_NUMBER}-integration-tests"
    environment:
      - DEBUG
      - "TEST_HOST=https://buildkite.com"
