version: '3'
services:

  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/home/pptruser/integration-tests"
    working_dir: /home/pptruser
    command: mocha integration-tests --no-timeout
    environment:
      - DEBUG
      - TEST_HOST
    links:
      - site

  site:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "3000"