version: '3'
services:

  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/integration-tests:rw"
    command: mocha --recursive integration-tests
    environment:
      - DEBUG
      - TEST_HOST
    links:
      - site

  site:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "3000"