version: '3.4'

services:
  integration-tests:
    build:
      context: .
      target: integration-tests
    environment:
      - "TEST_HOST=http://site:3000"
      - DEBUG
      - PERCY_TOKEN
      - IGNORE_HTTPS_ERRORS=true
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_BUILD_ID
    links:
      - site

  site:
    build: .
    expose:
      - "3000"
