version: '3.4'

services:
  integration-tests:
    image: "buildkiteci/site:site-build-${BUILDKITE_BUILD_NUMBER}-integration-tests"
    environment:
      - "TEST_HOST=http://site:3000"
      - DEBUG
      - PERCY_TOKEN
      - IGNORE_HTTPS_ERRORS=true
      - PRODUCTION_HEADERS=true
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_BUILD_ID
    links:
      - site

  site:
    image: "buildkiteci/site:site-build-${BUILDKITE_BUILD_NUMBER}-prod"
    expose:
      - "3000"
