steps:
  - label: ":pipeline::closed_lock_with_key:"
    command: "buildkite-agent pipeline upload .buildkite/pipeline.security.yml"

  - name: ":eslint:"
    command: yarn lint
    plugins:
      docker-compose#v1.8.2:
        run: site

  - name: ":flowtype:"
    command: yarn flow
    plugins:
      docker-compose#v1.8.2:
        run: site
    skip: "TODO"

  - name: ":package::mag:"
    command: yarn bundle-analyze
    artifact_paths: "bundle-analysis/*"
    plugins:
      docker-compose#v1.8.2:
        run: site

  - name: ":chrome::hammer:"
    agents:
      queue: elastic-builders
    artifact_paths: "integration-tests/screenshots/*"
    plugins:
      docker-compose#v1.8.2:
        run: tests
        config: docker-compose.integration-tests.yml

  - wait

  - label: ":docker: :package:"
    branches:
      - master
      - deploy-on-ecs
    agents:
      queue: elastic-builders
    plugins:
      ecr#v1.1.2:
        login: true
        account-ids: ${ECR_ACCOUNT_ID}
      docker-compose#v1.8.2:
        config: docker-compose.prod.yml
        push:
          - site:${ECR_REPOSITORY}:${BUILDKITE_BUILD_NUMBER}

  - wait

  - label: ":docker: :rocket:"
    branches: master
    concurrency: 1
    concurrency_group: site-deploy
    agents:
      queue: deploy
    command: scripts/deploy-ecs

    # 🤔
    # plugins:
    #   ecs-deploy#v1.0.0:
    #     cluster: site-example
    #     service: site
    #     task-family: site
    #     image: ${ECR_REPOSITORY}:${BUILDKITE_BUILD_NUMBER}

  - wait
  
  - label: ":partyparrot:"
    branches: master
    command: "buildkite-agent annotate --style success ':partyparrot: Deployed to https://buildkite.com/'"

  - wait

  - name: ":chrome::lightning:"
    branches: master
    agents:
      queue: elastic-builders
    artifact_paths: "integration-tests/screenshots/*"
    environment:
      - "TEST_HOST=https://buildkite.com"
    plugins:
      docker-compose#v1.8.2:
        run: tests
        config: docker-compose.integration-tests.yml