steps:

  - label: ":retirejs:"
    command: yarn run retire
    agents:
      # Because this is an hourly scheduled build, we don't want to use the
      # elastic agents because then the stack will never scale in. The
      # docker builders are our next best thing.
      queue: elastic-builders
    plugins:
      docker-compose#v2.5.1:
        # We check for frontend JS dep vulnerabilities in our dev image, because
        # that's before packaging etc
        config: docker-compose.yml
        run: site
