steps:

  - label: ":jest:"
    command: yarn test
    plugins:
      docker-compose#v1.5.1:
        run: site

  - label: ":percy:"
    plugins:
      docker-compose#v1.5.1:
        config: docker-compose.percy.yml
        run: percy
    skip: "Static export doesn't work with cached assets"

  - wait

  - label: ":docker: :package:"
    branches:
      - master
      - deploy-on-ecs
    plugins:
      ecr#v1.1.2:
        login: true
        account-ids: ${ECR_ACCOUNT_ID}
      docker-compose#v1.5.1:
        config: docker-compose.prod.yml
        push:
          - site:${ECR_REPOSITORY}:${BUILDKITE_BUILD_NUMBER}

  - wait

  - label: ":docker: :rocket:"
    branches:
      - master
      - deploy-on-ecs
    command: scripts/deploy-ecs

    # 🤔
    # plugins:
    #   ecs-deploy#v1.0.0:
    #     cluster: site-example
    #     service: site
    #     task-family: site
    #     image: ${ECR_REPOSITORY}:${BUILDKITE_BUILD_NUMBER}
